resources:
  - url: http://127.0.0.1:5000/posten-card.js
    type: module
views:
  - cards:
      - type: custom:posten-card
        name: Posten Card Development
        entity: sun.sun
        test_gui: true
